#!/bin/bash

echo "Building goem..."

# On Windows with MingW.
if [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]; then

    if [ ! -d ./_build ]; then
        mkdir ./_build
        go build -o _build/goem.exe main.go

        # Install goem to Go binary folder so it can be accessed from
        # command line as it should at least be in PATH environmental variable.
        cp ./_build/goem.exe $GOROOT/bin \
            && echo "Installed goem.exe to ${GOROOT}bin."
        rm -rf ./_build
    else
        echo "Aborting build, remove _build directory to continue."
    fi

else

    # On other environments e.g. Linux, Mac

    if [ ! -d ./_build ]; then
        mkdir ./_build
        go build -o _build/goem main.go
        cp _build/goem /usr/local/bin \
            && echo "Installed goem to /usr/local/bin."
        rm -rf ./_build
    else
        echo "Aborting build, remove _build directory to continue."
    fi

fi

